### ISSUE TITLE
tossing error when asking for KEYS thru wss

### ISSUE THREAD

**Issue by eswat2** [eswat2/fire-notes#1]
-- looking for username, which isn't passed to the KEYS request

```
/app/app.js:101 
Jul 28 21:21:34 fire-notes app/web.1:        let user = obj.id.toLowerCase(); 
Jul 28 21:21:34 fire-notes app/web.1:                         ^ 
Jul 28 21:21:34 fire-notes app/web.1:  TypeError: Cannot read property 'toLowerCase' of undefined 
Jul 28 21:21:34 fire-notes app/web.1:      at WebSocket.ws.on (/app/app.js:101:24) 
Jul 28 21:21:34 fire-notes app/web.1:      at emitTwo (events.js:106:13) 
Jul 28 21:21:34 fire-notes app/web.1:      at WebSocket.emit (events.js:191:7) 
Jul 28 21:21:34 fire-notes app/web.1:      at Receiver.ontext (/app/node_modules/ws/lib/WebSocket.js:841:10) 
Jul 28 21:21:34 fire-notes app/web.1:      at /app/node_modules/ws/lib/Receiver.js:536:18 
Jul 28 21:21:34 fire-notes app/web.1:      at /app/node_modules/ws/lib/Receiver.js:368:7 
Jul 28 21:21:34 fire-notes app/web.1:      at /app/node_modules/ws/lib/PerMessageDeflate.js:249:5 
Jul 28 21:21:34 fire-notes app/web.1:      at afterWrite (_stream_writable.js:361:3) 
Jul 28 21:21:34 fire-notes app/web.1:      at onwrite (_stream_writable.js:352:7) 
Jul 28 21:21:34 fire-notes app/web.1:      at WritableState.onwrite (_stream_writable.js:89:5) 
Jul 28 21:21:34 fire-notes app/web.1:      at afterTransform (_stream_transform.js:79:3) 
Jul 28 21:21:34 fire-notes app/web.1:      at TransformState.afterTransform (_stream_transform.js:54:12) 
Jul 28 21:21:34 fire-notes app/web.1:      at Zlib.callback (zlib.js:639:5) 
```

**Comment by eswat2** [comment]
resolved -- b5ee497ce09e8316db75969d2146611aadd72242
